### ISSUE TITLE
Add Jest testing framework

### ISSUE THREAD

**Issue by tjnicolaides** [tjnicolaides/job-scraper#7]
This repo needs a testing framework, so we can safely modify our code going forward. For modern JS projects, Jest is the most widely supported assertion library.

## Expected result(s):
- [x] Jest is added as an npm dependency
- [x] `npm run test` runs as an alias for jest
- [x] When `npm run test` runs, it runs one test suite to prove the framework is working as expected
   - a test for `src/index.js` would live at `test/index.test.js`, for example
- [x] `npm run test` is added to Github Actions, and when it fails, it "breaks" a build.

## Other information:

- https://jestjs.io/docs/en/getting-started

**Comment by stevennic22** [comment]
Fixed through #17
