### ISSUE TITLE
Load jobjawn data as a dependency of this project

### ISSUE THREAD

**Issue by tjnicolaides** [tjnicolaides/job-scraper#9]
We want the JSON data from another public project: https://github.com/jobjawn/dataDump. Luckily, `npm` can accept any public Github repo as a dependency. 

## Expected result(s):
- [x] https://github.com/jobjawn/dataDump is added as an npm dependency of this project
- [x] a `postinstall` step, or something similar, copies the `.json` files from the node_modules directory into a directory where the `src/*.js` files can access the data
- [x] the contents of this directory are ignored by git, but the directory itself is tracked with a `.gitkeep`
- [x] when the project is deployed to Google Cloud Run, these JSON files are part of the payload

## Other information:
- https://stackoverflow.com/questions/34781630/how-to-automatically-copy-files-from-package-to-local-directory-via-postinstall
- https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly

**Comment by stevennic22** [comment]
Possible method to pull the data locally: https://www.npmjs.com/package/git-clone

Regarding the first bit, it appears that adding a git repo as a dependency requires that the repo be an npm package in some fashion. Would an install step that checks for the existence of the repo be sufficient?

**Comment by tjnicolaides** [comment]
Good reading of the docs, and good research. I thought it was good without, but proof you are right:

```bash
√ thomas_nicolaides at TJs-MacBook in ~/Sites/job-scraper 
 $ npm install jobjawn/dataDump                                                                                                                                                 master
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: github:jobjawn/dataDump.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thomas_nicolaides/.npm/_logs/2020-03-26T13_54_28_000Z-debug.log
```
